all:
  hosts:
    xdp1:
      ansible_host: swystems.xdp1
      devs:
        - enp65s0f0np0
      ibdevs:
        - rocep65s0f0
      ip: "10.10.1.1"
    xdp2:
      ansible_host: swystems.xdp2
      devs:
        - enp65s0f0np0
      ibdevs:
        - rocep65s0f0
      ip: "10.10.1.2"

tx_nodes:
  hosts:
    xdp1

rx_nodes:
  hosts:
    xdp2