all:
  vars:
    interval: 10000 # ns
    #packets: 8640000000
    packets: 1000000
    run_isolated: false
    stress: false
    debug: 0
    execute_command: "{{ ('taskset -c ' + isolated_cores_but_last + ' ') if run_isolated else '' }}"
    timeout: "{{ ((interval * packets * 1.3) / 1000000000 + 1) | round | int }}"
    measurement: 0
    sync_wait: "yes"
