all:
  vars:
    interval: 10000 # ns
    packets: 2160000000 # 12h
    run_isolated: false
    debug: 1
    execute_command: "{{ 'taskset -c ' + isolated_cores + ' ' if run_isolated else '' }}"
    timeout: "{{ ((interval * packets * 1.3) / 1000000000 + 1) | round | int }}"
    measurement: 2
    sync_wait: "no"
