all:
  hosts:
    xdp1:
      ansible_host: swystems.xdp1
      devs:
        - ens1f1np1
      ibdevs:
        - rocep3s0f1
      ip: "10.10.1.2"
    xdp2:
      ansible_host: swystems.xdp2
      devs:
        - ens1f1np1
      ibdevs:
        - rocep3s0f1
      ip: "10.10.1.1"

  vars:
    ansible_user: mdr
    isolated_cores: "11"
    cpu_freq: 2400000000 # 2.4 GHz
    base_dir: "/users/{{ ansible_user }}"

tx_nodes:
  hosts:
    xdp1

rx_nodes:
  hosts:
    xdp2