all:
  hosts:
    xdp1:
      ansible_host: swystems.xdp1
      devs:
        - ens1f1np1
      ibdevs:
        - rocep3s0f1
      ip: "10.10.1.2"
    xdp2:
      ansible_host: swystems.xdp2
      devs:
        - ens1f1np1
      ibdevs:
        - rocep3s0f1
      ip: "10.10.1.1"

tx_nodes:
  hosts:
    xdp1

rx_nodes:
  hosts:
    xdp2