---
- hosts: all
  gather_facts: True
  gather_subset:
    - "!all"
  tasks:
    - name: Build pingpong programs
      block:
        - name: Build XDP programs
          shell: |
            cd {{ base_dir }}/xdp/build
            cmake ..
            make clean
            make
        - name: Build RDMA programs
          shell: |
            cd {{ base_dir }}/rdma/build
            cmake ..
            make clean
            make

    - name: Reload ldconfig
      become: yes
      shell: |
        ldconfig
