---
- hosts: all
  gather_facts: no
  tasks:
    - name: Upload source files
      #become: yes
      synchronize:
        src: "../../"
        dest: "{{ base_dir }}"
        rsync_opts:
          - "--exclude=.*"
          - "--exclude=analysis/"
          - "--exclude=ansible/"
          - "--chown={{ ansible_user }}:{{ ansible_user }}"