---
- hosts: all
  gather_facts: False
  tasks:
    - name: Upload source files
      become: yes
      synchronize:
        src: "{{ playbook_dir }}/.."
        dest: "{{ base_dir }}"
        rsync_opts:
          - "--exclude=.*"
          - "--exclude=analysis/"
          - "--exclude=ansible/"
          - "--chown={{ ansible_user }}:{{ ansible_user }}"