all:
  hosts:
    xdp1:
      ansible_host: swystems.xdp1
      devs:
        - ens1f1np1
      ibdevs:
        - rocep7s0f1
    xdp2:
      ansible_host: swystems.xdp2
      devs:
        - ens1f1np1
      ibdevs:
        - rocep7s0f1

  vars:
    ansible_user: mdr
    isolated_cores: "11"
    cpu_freq: 2400000000 # 2.4 GHz
