all:
  hosts:
    xdp1:
      ansible_host: swystems.xdp1
      devs:
        - ens1f1np1 # xl170
        #- enp65s0f0np0 # c6525-25g
      ibdevs:
        - rocep3s0f1 # xl170
        #- rocep65s0f0 # c6525-25g
    xdp2:
      ansible_host: swystems.xdp2
      devs:
        - ens1f1np1 # xl170
        #- enp65s0f0np0 # c6525-25g
      ibdevs:
        - rocep3s0f1 # xl170
        #- rocep65s0f0 # c6525-25g

  vars:
    ansible_user: mdr
    isolated_cores: "11"
    cpu_freq: 2400000000 # 2.4 GHz
