all:
  hosts:
    xdp1:
      ansible_host: swystems.xdp1
      devs:
        # - ens1f1np1
        - enp65s0f0np0
      ibdevs:
        # - rocep7s0f1
        - rocep65s0f0
    xdp2:
      ansible_host: swystems.xdp2
      devs:
        - enp65s0f0np0
      ibdevs:
        - rocep65s0f0

  vars:
    ansible_user: mdr
    isolated_cores: "11"
    cpu_freq: 2400000000 # 2.4 GHz
