---
- hosts: all
  gather_facts: True
  gather_subset:
    - "!all"
  vars:
    kernel_version: "6.6.19"
  tasks:
    - name: Update packages
      become: yes
      shell: |
        apt update
        apt upgrade -y

    - name: Install base packages
      become: yes
      apt:
        pkg:
          - build-essential
          - automake
          - autoconf
          - pkg-config
          - make
          - cmake
          - clang
          - git

    - name: Setup kernel parameters
      block:
        - name: Modify GRUB file
          become: yes
          lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX='
            line: 'GRUB_CMDLINE_LINUX="isolcpus={{isolated_cores}} nohz_full={{isolated_cores}} rcu_nocbs={{isolated_cores}} default_hugepagesz=1G hugepagesz=1G hugepages=8 iommu=pt intel_iommu=on"'
            state: present
        - name: Update grub
          become: yes
          shell: |
            update-grub2

    - name: Update kernel to ${kernel_version}
      block:
        - name: Download ubuntu-mainline-kernel.sh
          become: yes
          get_url:
            url: "https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh"
            dest: /opt/ubuntu-mainline-kernel.sh
            mode: 0755
        - name: Install kernel {{ kernel_version }}
          become: yes
          shell: |
            /opt/ubuntu-mainline-kernel.sh -i {{ kernel_version }}
        - name: Reboot the system
          become: yes
          reboot:
        - name: Fix apt packages
          become: yes
          shell: |
              apt --fix-broken install -y

    - name: Add /usr/local/lib to ldconfig
      block:
        - name: Add /usr/local/lib to ldconfig
          become: yes
          # make sure that /etc/ld.so.conf.d/local.conf exists and contains /usr/local/lib, /usr/local/lib64, and /usr/lib64
          blockinfile:
            path: /etc/ld.so.conf.d/local.conf
            block: |
              /usr/local/lib
              /usr/local/lib64
              /usr/lib64
            state: present
            create: yes
        - name: Update ldconfig
          become: yes
          shell: |
            ldconfig
