---
- hosts: all
  gather_facts: True
  gather_subset:
    - "!all"
  tasks:
    - name: Install RDMA packages
      become: yes
      apt:
        pkg:
          - rdma-core
          - libibverbs1
          - librdmacm1
          - libtool
          - ibutils
          - ibverbs-utils
          - rdmacm-utils
          - infiniband-diags
          - perftest
          - librdmacm-dev
          - libibverbs-dev
          - numactl
          - libnuma-dev
          - libnl-3-200
          - libnl-route-3-200
          - libnl-route-3-dev
          - libnl-utils

    - name: Rename IB node descriptors
      become: yes
      shell: |
        hostname -s > /sys/class/infiniband/{{ item }}/node_desc
      loop: "{{ibdevs}}"

    # needed?
    - name: Clone and build the RDMA-core repo
      shell: |
        git clone https://github.com/linux-rdma/rdma-core.git
        cd rdma-core/
        ./build.sh
