[package]
name = "rdma_rc_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
common = {path = "../common/"} 
pingpong = {path = "../pingpong/"}
rdma = {git="https://github.com/JacobSalvi/rdma.git"}
libc = "*"
